server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Прокси API к боевому бэкенду
    location /api/ {
        proxy_pass http://api:3000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Верификатор статика (если соберём)
    location /verifier/ {
        alias /usr/share/nginx/html/verifier/;
        try_files $uri $uri/ =404;
    }

    # ToS/Privacy
    location = /terms.html { try_files $uri =404; }
    location = /privacy.html { try_files $uri =404; }
}
